In [9]:
import pandas as pd
import numpy as np
arr=np.array([1,2,3,4])
s=pd.Series(arr,index=['Raj','Gauri','Reena','Ganesh'],name="Students")
s.index
s.dtype
s.shape #tuple with no of elements
s.size # total no of elems
s.name

'Students'

In [10]:
print(s.head())
print(s.tail())
print(s.sum())
print(s.mean())
print(s.max())
print(s.min())
print(s.sort_values())
print(s.unique()) #distinct values
print(s.nunique()) #count of distinct values
print(s.apply(lambda x:x*x))

Raj       1
Gauri     2
Reena     3
Ganesh    4
Name: Students, dtype: int64
Raj       1
Gauri     2
Reena     3
Ganesh    4
Name: Students, dtype: int64
10
2.5
4
1
Raj       1
Gauri     2
Reena     3
Ganesh    4
Name: Students, dtype: int64
[1 2 3 4]
4
Raj        1
Gauri      4
Reena      9
Ganesh    16
Name: Students, dtype: int64

In [11]:
data={
  'Name':['Aditi','Rohan','Meera'],
  'Age':[21,20,23]
}
df=pd.DataFrame(data)
df

    Name  Age
0  Aditi   21
1  Rohan   20
2  Meera   23

In [12]:
records=[
  {'Name':'Aditi','Age':13},
  {'Name':'Rohan','Age':24}
]
df=pd.DataFrame(records)
print(df)

    Name  Age
0  Aditi   13
1  Rohan   24

In [39]:
rows=[['Aditi',21],['Rohan',23],['Ravi'],[None,34],[],['Aditi',31]]
df=pd.DataFrame(rows,columns=['Name','Age'])
print(df)

    Name   Age
0  Aditi  21.0
1  Rohan  23.0
2   Ravi   NaN
3   None  34.0
4   None   NaN
5  Aditi  31.0

In [17]:
df.info()
df.describe()
df.columns
df.index
df['Name'].value_counts() #freq of each unique value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

Name
Aditi    1
Rohan    1
Name: count, dtype: int64

In [23]:
df[df['Name'].isin(['Aditi','Raghav'])]
df.query("Age>22 and Name=='Ishita'")
df.isnull().sum()
df.notnull() #opposite of isnull

   Name   Age
0  True  True
1  True  True

In [ ]:
df.dropna(subset=['Age']) #drops only where age is missing
df.dropna(how='all') #drops only rows where every col is null

    Name   Age
0  Aditi  21.0
1  Rohan  23.0
2   Ravi   NaN
3   None  34.0

In [32]:
df['Gender']=['Female','Male','Male','Female',None]
df['Gender']=df['Gender'].replace({'Male':'M','Female':'F'})
df=df.rename(columns={'Name':'Stud_Name'})
df

  Stud_Name   Age Gender
0     Aditi  21.0      F
1     Rohan  23.0      M
2      Ravi   NaN      M
3      None  34.0      F
4      None   NaN   None

In [ ]:
df.duplicated() #check if col have duplicates and return bool value
df.drop_duplicates()
df.drop_duplicates(subset=['Name'],keep='last') #keep- first,last

    Name   Age
0  Aditi  21.0
1  Rohan  23.0
2   Ravi   NaN
3   None  34.0
4   None   NaN
5  Aditi  31.0

In [41]:
df['Eligible']=df['Age'].map(lambda e: 'Adult' if e>=18 else "Child" if e<=10 else "Teenager")
df

    Name   Age  Eligible
0  Aditi  21.0     Adult
1  Rohan  23.0     Adult
2   Ravi   NaN  Teenager
3   None  34.0     Adult
4   None   NaN  Teenager
5  Aditi  31.0     Adult

In [ ]:
# vectorization  operations - used to apply operations to pandas data structure at once instead of loop