In [40]:
# Student Performance Project

import pandas as pd
# load dataset
df=pd.read_csv(r"C:\Users\ishit\Downloads\student_performance_project.csv")
df

    StudentID             Name Gender       City  Math  Science  English
0           1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0
1           2      Rohan Verma      F     Mumbai  78.0     97.0     60.0
2           3       Meera Nair      F      Delhi  90.0     81.0     70.0
3           4      Karan Mehta      F      Delhi  45.0     41.0     70.0
4           5        Sneha Rao      M      Delhi  91.0     80.0     51.0
..        ...              ...    ...        ...   ...      ...      ...
56         57     Qasim Sheikh      M      Delhi  49.0     55.0     91.0
57         58  Reema Chowdhury      F    Kolkata  61.0     47.0     33.0
58         59     Sahil Kapoor      M       Pune  60.0     59.0     34.0
59         60    Tara Krishnan      F    Chennai  79.0      NaN     81.0
60          1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0

[61 rows x 7 columns]

In [41]:
# look at data quality
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  61 non-null     int64
 1   Name       61 non-null     object
 2   Gender     61 non-null     object
 3   City       61 non-null     object
 4   Math       57 non-null     float64
 5   Science    58 non-null     float64
 6   English    58 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 3.5+ KB

In [42]:
# data cleaning
df['Math']=df['Math'].fillna(df['Math'].mean())
df['Science']=df['Science'].fillna(df['Science'].mean())
df['English']=df['English'].fillna(df['English'].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  61 non-null     int64
 1   Name       61 non-null     object
 2   Gender     61 non-null     object
 3   City       61 non-null     object
 4   Math       61 non-null     float64
 5   Science    61 non-null     float64
 6   English    61 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 3.5+ KB

In [43]:
# removing duplicates
print(df.shape)
df=df.drop_duplicates()
print(df.shape)

(61, 7)
(60, 7)

In [44]:
# filtering students
res = df[(df['Math'] > 50) & (df['Science'] > 50) & (df['English'] > 50)]
res

df['Result'] = ((df['Math'] > 50) & (df['Science'] > 50) & (df['English'] > 50)).map({True: 'Pass', False: 'Fail'})
df[['Math', 'Science', 'English', 'Result']].head()

C:\Users\ishit\AppData\Local\Temp\ipykernel_18948\2387258132.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Result'] = ((df['Math'] > 50) & (df['Science'] > 50) & (df['English'] > 50)).map({True: 'Pass', False: 'Fail'})

   Math  Science  English Result
0  33.0     33.0     74.0   Fail
1  78.0     97.0     60.0   Pass
2  90.0     81.0     70.0   Pass
3  45.0     41.0     70.0   Fail
4  91.0     80.0     51.0   Pass

In [21]:
# Student - wise Analysis
df['total_marks'] = df[['Math', 'Science', 'English']].sum(axis=1)
df[['Math', 'Science', 'English', 'total_marks']].head()

C:\Users\ishit\AppData\Local\Temp\ipykernel_18948\2882844173.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_marks'] = df[['Math', 'Science', 'English']].sum(axis=1)

   Math  Science  English  total_marks
0  33.0     33.0     74.0        140.0
1  78.0     97.0     60.0        235.0
2  90.0     81.0     70.0        241.0
3  45.0     41.0     70.0        156.0
4  91.0     80.0     51.0        222.0

In [54]:
# total, avg and ranking
student_df = df.copy()
student_df['Average_Marks'] = student_df[['Math', 'Science', 'English']].mean(axis=1)
student_df['Rank'] = student_df['Average_Marks'].rank(method='average', ascending=False)
student_df = student_df.sort_values(by='Rank')
student_df.head()

,StudentID,Name,Gender,City,Math,Science,English,Result,Average_Marks,Rank
51,52,Lavanya Menon,F,Pune,93.0,98.0,96.000000,Pass,95.666667,1.0
47,48,Hitesh Goyal,F,Pune,91.0,98.0,90.000000,Pass,93.000000,2.0
37,38,Sameer Ansari,F,Chennai,88.0,82.0,90.000000,Pass,86.666667,3.0
2,3,Meera Nair,F,Delhi,90.0,81.0,70.000000,Pass,80.333333,4.0
52,53,Mohit Ahluwalia,F,Chennai,95.0,80.0,63.465517,Pass,79.488506,5.0

In [53]:
# Gender wise and city wise analysis
print(df.groupby(['City','Gender'])['Math'].agg(['count','min','max']).round(2))
print(df.groupby(['City','Gender'])['Science'].agg(['count','min','max']).round(2))
print(df.groupby(['City','Gender'])['English'].agg(['count','min','max']).round(2))

                  count   min    max
City      Gender
Bengaluru F           5  33.0  65.00
          M           3  31.0  76.00
Chennai   F           6  36.0  95.00
          M           5  47.0  97.00
Delhi     F           5  45.0  90.00
          M           3  48.0  91.00
Kolkata   F           3  46.0  61.98
          M           8  30.0  98.00
Mumbai    F          10  35.0  87.00
          M           3  58.0  98.00
Pune      F           5  55.0  93.00
          M           4  30.0  60.00
                  count   min   max
City      Gender
Bengaluru F           5  33.0  77.0
          M           3  30.0  74.0
Chennai   F           6  36.0  94.0
          M           5  35.0  93.0
Delhi     F           5  41.0  81.0
          M           3  49.0  80.0
Kolkata   F           3  31.0  47.0
          M           8  39.0  87.0
Mumbai    F          10  47.0  97.0
          M           3  45.0  74.0
Pune      F           5  41.0  98.0
          M           4  59.0  86.0
                  count   min   max
City      Gender
Bengaluru F           5  37.0  74.0
          M           3  30.0  56.0
Chennai   F           6  38.0  90.0
          M           5  51.0  89.0
Delhi     F           5  46.0  83.0
          M           3  51.0  91.0
Kolkata   F           3  33.0  89.0
          M           8  31.0  96.0
Mumbai    F          10  31.0  86.0
          M           3  45.0  65.0
Pune      F           5  35.0  96.0
          M           4  34.0  73.0

In [55]:
# combined groupby report
combined_report = df.groupby(['City', 'Gender']).agg(
	students=('Math', 'count'),
	math_min=('Math', 'min'),
	math_max=('Math', 'max'),
	math_mean=('Math', 'mean'),
	science_min=('Science', 'min'),
	science_max=('Science', 'max'),
	science_mean=('Science', 'mean'),
	english_min=('English', 'min'),
	english_max=('English', 'max'),
	english_mean=('English', 'mean')
).round(2)
combined_report

                  students  math_min  math_max  math_mean  science_min  \
City      Gender
Bengaluru F              5      33.0     65.00      51.60         33.0
          M              3      31.0     76.00      56.33         30.0
Chennai   F              6      36.0     95.00      66.17         36.0
          M              5      47.0     97.00      71.40         35.0
Delhi     F              5      45.0     90.00      68.60         41.0
          M              3      48.0     91.00      62.67         49.0
Kolkata   F              3      46.0     61.98      56.33         31.0
          M              8      30.0     98.00      56.75         39.0
Mumbai    F             10      35.0     87.00      60.80         47.0
          M              3      58.0     98.00      79.33         45.0
Pune      F              5      55.0     93.00      72.00         41.0
          M              4      30.0     60.00      51.75         59.0

                  science_max  science_mean  english_min  english_max  \
City      Gender
Bengaluru F              77.0         60.80         37.0         74.0
          M              74.0         52.33         30.0         56.0
Chennai   F              94.0         67.94         38.0         90.0
          M              93.0         57.80         51.0         89.0
Delhi     F              81.0         62.40         46.0         83.0
          M              80.0         61.33         51.0         91.0
Kolkata   F              47.0         38.33         33.0         89.0
          M              87.0         64.75         31.0         96.0
Mumbai    F              97.0         65.86         31.0         86.0
          M              74.0         61.67         45.0         65.0
Pune      F              98.0         73.72         35.0         96.0
          M              86.0         72.00         34.0         73.0

                  english_mean
City      Gender
Bengaluru F              55.80
          M              46.00
Chennai   F              71.08
          M              70.69
Delhi     F              66.49
          M              77.67
Kolkata   F              64.67
          M              59.25
Mumbai    F              62.90
          M              57.00
Pune      F              71.00
          M              53.00

In [56]:
# topper list
topper_list = student_df.head(5)
topper_list

,StudentID,Name,Gender,City,Math,Science,English,Result,Average_Marks,Rank
51,52,Lavanya Menon,F,Pune,93.0,98.0,96.000000,Pass,95.666667,1.0
47,48,Hitesh Goyal,F,Pune,91.0,98.0,90.000000,Pass,93.000000,2.0
37,38,Sameer Ansari,F,Chennai,88.0,82.0,90.000000,Pass,86.666667,3.0
2,3,Meera Nair,F,Delhi,90.0,81.0,70.000000,Pass,80.333333,4.0
52,53,Mohit Ahluwalia,F,Chennai,95.0,80.0,63.465517,Pass,79.488506,5.0